### PR TITLE
Enable Windows builds

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
This PR currently has inscrutible `conda` solve errors.
```
Unsatisfiable dependencies for platform win-64
``` 

Will revisit once `mambabuild` becomes an option:
https://github.com/conda-forge/conda-smithy/pull/1441

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:
<snip indecipherable conda error>
```
...let's try `build_with_mambabuild` 🤞

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
`boa` has been released. Will give it another go...

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Looks like the `boa` feedstock hasn't yet passed - https://github.com/conda-forge/boa-feedstock/pull/21

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Woot! I've got an actionable error message! 🎉 
```
Mamba failed to solve:
 - python >=3.9,<3.10.0a0
 - trampoline >=0.1.2
 - scipy ~=1.5.0
 - pytorch >=1.6.0
 - typing_extensions
 - boltons >=20.2.1
 - python_abi 3.9.* *_cp39
 - numpy ~=1.19.0
 - vs2015_runtime >=14.16.27012
 - vc >=14.1,<15.0a0
 - blist

with channels:

The reported errors are:
   Encountered problems while solving.
   Problem: package pytorch-1.6.0-cpu_py37h538a6d7_0 requires python >=3.7,<3.8.0a0, but none of the providers can be installed
```
:point_up: thanks @wolfv - `mamba` is such an important tool to enable people to debug these types of issue.

**Comment by dhirschfeld** [comment]
Looks like `conda-forge` doesn't yet build `pytorch` for Windows:
https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
Cool, I'm glad that this works now

**Pull request merged**
